### ISSUE TITLE
Retorno

### ISSUE THREAD

**Issue by YuriFontella** [edvaldoszy/pagseguro-nodejs#1]
@edvaldoszy estou testando sua lib, só que a única vez que eu integrei o pagseguro foi no ruby on rails, e ele me retornava uma url, onde eu redirecionava o usuário. Aqui ele está me retornando um xml, e sinceramente não sei bem oq fazer.

Se puder me dar alguma dica.

**Comment by edvaldoszy** [comment]
Boa noite, Yuri!

Você conseguiu alguma coisa?

**Comment by YuriFontella** [comment]
Sim, li a documentação API de Pagamentos do Pagseguro. E tudo que eu preciso é a tag code do xml para usar na url.

Utilizei o xml2json e deu tudo certo.

**Comment by edvaldoszy** [comment]
Bacana! Precisando de alguma coisa, estamos ai 👍
